name: ci
on: [push, pull_request]

jobs:
  opam:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ocaml:
          - 5
          - 4
          - 4.03.x
        include:
          - os: macos-latest
            ocaml: 4
          - os: windows-latest
            ocaml: 4
            system: msys2
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: tobil4sk/setup-ocaml@feature/msys2
        with:
          ocaml-compiler: ${{ matrix.ocaml }}
          windows-environment: ${{ matrix.system }}

      - run: |
          echo $env:PATH
          where.exe sh

          $env:PATH="C:\msys64\usr\bin;$env:PATH"
          where.exe sh

      # - run: tree D:\cygwin
      #   if: matrix.os == 'windows-latest'

      - run: opam install -y --deps-only .
      - run: opam exec -- dune build -p luv

  old-libuv:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.x
      - run: opam install -y --deps-only .
      - run: git clone https://github.com/libuv/libuv.git
        working-directory: ..
      - run: |
          git checkout v1.3.0
          ./autogen.sh
          sh configure
          make
          sh libtool --mode install cp libuv.la $(pwd)
        working-directory: ../libuv
      - run: opam exec -- dune build -p luv
        env:
          LUV_USE_SYSTEM_LIBUV: yes
          C_INCLUDE_PATH: ${{ github.workspace }}/../libuv/include
          LIBRARY_PATH: ${{ github.workspace }}/../libuv

  # esy builds are broken due to an upstream bug that is not worth working
  # around in luv, but should be fixed in esy:
  #
  #   https://github.com/esy/esy/issues/1440
  #
  # esy:
  #   strategy:
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - macos-latest
  #         - windows-latest
  #     fail-fast: false
  #   runs-on: ${{ matrix.os }}
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: recursive
  #     - run: npm install esy
  #     - run: npx esy install
  #     - run: npx esy build
